name: moduleTest

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package files (1/2) - Collect files
        run: |
          mkdir release
          cp LICENSE release/
          cp README.md release/
          cp src/cfg_docker/Dockerfile release/
          cp src/src_paperPassBox/set.sh release/

      - name: Package files (2/2) - Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release

      - name: Prepare Docker test container
        run: |
          cp -r ./release ./deployment
          cd deployment
          docker build -t myapp:latest .
          docker run -d -p 2222:22 --name myapp_container myapp:latest
          docker ps -a  # List all containers for debugging

      - name: Wait for container to start
        run: sleep 30  # Wait to ensure the SSH service starts

      - name: Check container logs
        run: docker logs myapp_container  # Show container logs for debugging

      - name: Check SSH configuration
        run: |
          docker exec myapp_container grep 'PermitRootLogin' /etc/ssh/sshd_config
          docker exec myapp_container grep 'root' /etc/shadow
          docker exec myapp_container grep 'user' /etc/shadow

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install dependencies and run tests
        run: |
          cp -R src/src_paperPassBox_test test
          cd test
          pip install -r requirements.txt
          pytest
